#define _CRT_SECURE_NO_WARNINGS 1

#include"SeqList.h"


void TestSeqList1()
{
	SL s;
	SeqListInit(&s);
	SeqListPushBack(&s, 1);
	SeqListPushBack(&s, 2);
	SeqListPushBack(&s, 3);
	SeqListPushBack(&s, 4);
	SeqListPushBack(&s, 8);

	SeqListPrintf(&s);

	SeqListPopBack(&s);

	SeqListPrintf(&s);

	SeqListPushFront(&s,5);

	SeqListPrintf(&s);

	SeqListPopFront(&s);

	SeqListPrintf(&s);

}

int main()
{
	TestSeqList1();

	return 0;
}
